# Generated by Django 5.0.6 on 2024-06-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=3)),
                ('nombre', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
    ]
